import type { Metadata } from "next";

import "./globals.css";
//import "@copilotkit/react-ui/styles.css";
import "@copilotkit/react-core/v2/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
          {children}
      </body>
    </html>
  );
}
